/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fastspim_NativeSPIMReconstructionCuda */

#ifndef _Included_fastspim_NativeSPIMReconstructionCuda
#define _Included_fastspim_NativeSPIMReconstructionCuda
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint JNICALL Java_fastspim_NativeSPIMReconstructionCuda_getNumCudaDevices(
		JNIEnv *env,
		jclass);

JNIEXPORT jstring JNICALL Java_fastspim_NativeSPIMReconstructionCuda_getCudaDeviceName(
		JNIEnv *env,
		jclass,
		jint deviceIdx);

JNIEXPORT void JNICALL Java_fastspim_NativeSPIMReconstructionCuda_setCudaDevice(
		JNIEnv *env,
		jclass,
		jint deviceIdx);

JNIEXPORT void JNICALL Java_fastspim_NativeSPIMReconstructionCuda_transform16Interactive(
		JNIEnv *env,
		jclass,
		jobjectArray data,
		jint w,
		jint h,
		jint d,
		jfloatArray invMatrix,
		jint targetW,
		jint targetH,
		jint targetD,
		jobject callback);

JNIEXPORT void JNICALL Java_fastspim_NativeSPIMReconstructionCuda_transform8(
		JNIEnv *env,
		jclass,
		jobjectArray data,
		jint w,
		jint h,
		jint d,
		jfloatArray invMatrix,
		jint targetW,
		jint targetH,
		jint targetD,
		jstring outfile,
		jboolean createTransformedMasks,
		jint border,
		jfloat zspacing,
		jstring maskfile);

JNIEXPORT void JNICALL Java_fastspim_NativeSPIMReconstructionCuda_transform16(
		JNIEnv *env,
		jclass,
		jobjectArray data,
		jint w,
		jint h,
		jint d,
		jfloatArray invMatrix,
		jint targetW,
		jint targetH,
		jint targetD,
		jstring outfile,
		jboolean createTransformedMasks,
		jint border,
		jfloat zspacing,
		jstring maskfile);



JNIEXPORT void JNICALL Java_fastspim_NativeSPIMReconstructionCuda_deconvolve(
		JNIEnv *env,
		jclass,
		jobjectArray inputfiles,
		jstring outputfile,
		jint dataW,
		jint dataH,
		jint dataD,
		jobjectArray weightfiles,
		jobjectArray kernelfiles,
		jint kernelH,
		jint kernelW,
		jint psfType,
		jint nViews,
		jint iterations,
		jint bitDepth);

JNIEXPORT void JNICALL Java_fastspim_NativeSPIMReconstructionCuda_deconvolve_1quit8(
		JNIEnv *env,
		jclass clazz);

JNIEXPORT void JNICALL Java_fastspim_NativeSPIMReconstructionCuda_deconvolve_1quit16(
		JNIEnv *env,
		jclass clazz);

JNIEXPORT void JNICALL Java_fastspim_NativeSPIMReconstructionCuda_deconvolve_1interactive8(
		JNIEnv *env,
		jclass clazz,
		jint iterations);

JNIEXPORT void JNICALL Java_fastspim_NativeSPIMReconstructionCuda_deconvolve_1interactive16(
		JNIEnv *env,
		jclass clazz,
		jint iterations);



JNIEXPORT void JNICALL Java_fastspim_NativeSPIMReconstructionCuda_deconvolve_1init(
		JNIEnv *env,
		jclass clazz,
		jint dataW,
		jint dataH,
		jint dataD,
		jobjectArray weightfiles,
		jobjectArray kernelfiles,
		jint kernelH,
		jint kernelW,
		jint iterationType,
		jint nViews,
		jint bitDepth);
#ifdef __cplusplus
}
#endif
#endif
